packages:
  - "tools/*"
  - "packages/*"
  - "examples"
catalog:
  "prettier": ^3.3.3
  "turbo": ^2.3.3
  "typescript": ^5.5.4
  "@eslint/js": "^9.16.0"
  "typescript-eslint": "^8.17.0"
  "eslint-plugin-vue": "^9.32.0"
  "globals": "^15.13.0"
  "eslint": "^9.16.0"
  "@vueuse/core": "^12.0.0"
  "@vueuse/motion": "^2.2.6"
  "vue": "^3.5.13"
  "uuid": "^11.0.3"
  "csstype": "^3.0.0"
  "@vitejs/plugin-vue": "^5.2.1"
  "vue-tsc": "^2.1.10"
  "vite": "^6.0.1"
  "vite-plugin-dts": "^4.3.0"
  "unocss": "^0.65.1"
  "@unocss/reset": "^0.65.1"
